name: ebook_builder
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  attributed_text: ^0.3.2
  bitsdojo_window: ^0.1.6
  build_runner: ^2.4.11
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  get: 4.6.6
  google_fonts: null
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.4
  super_editor: ^0.2.7
  super_editor_markdown: ^0.1.5

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

dependency_overrides:
  super_editor:
    git:
      url: https://github.com/superlistapp/super_editor
      path: super_editor
      ref: main # or "main"
  super_editor_markdown:
    git:
      url: https://github.com/superlistapp/super_editor
      path: super_editor_markdown
      ref: main
  super_text_layout:
    git:
      url: https://github.com/superlistapp/super_editor
      path: super_text_layout
      ref: main
  attributed_text:
    git:
      url: https://github.com/superlistapp/super_editor
      path: attributed_text
      ref: main

flutter:
  uses-material-design: true
